import type { components } from '../schema';
import type * as T from '../../types';

type S = components['schemas'];
type Extra<Local, Wire> = Exclude<keyof Local, keyof Wire>;
type None<X extends never> = X;

export type CheckAgentJobCreate = None<Extra<T.AgentJobCreate, S['AgentJobCreate']>>;
export type CheckAgentJobFromTemplate = None<Extra<T.AgentJobFromTemplate, S['AgentJobFromTemplate']>>;
export type CheckAgentJobUpdate = None<Extra<T.AgentJobUpdate, S['AgentJobUpdate']>>;
export type CheckAgentJobFeedback = None<Extra<T.AgentJobFeedback, S['AgentJobFeedbackResponse']>>;
export type CheckAgentJobFeedbackCreate = None<Extra<T.AgentJobFeedbackCreate, S['AgentJobFeedbackCreate']>>;
export type CheckAgentJobFeedbackListResponse = None<Extra<T.AgentJobFeedbackListResponse, S['AgentJobFeedbackListResponse']>>;
export type CheckAgentJobExtractedMemory = None<Extra<T.AgentJobExtractedMemory, S['AgentJobExtractedMemoryResponse']>>;
export type CheckAgentJobMemoryExtractResponse = None<Extra<T.AgentJobMemoryExtractResponse, S['AgentJobMemoryExtractResponse']>>;
export type CheckAgentJobMemory = None<Extra<T.AgentJobMemory, S['AgentJobMemoryResponse']>>;
export type CheckAgentJobMemoryListResponse = None<Extra<T.AgentJobMemoryListResponse, S['AgentJobMemoryListResponse']>>;
export type CheckAgentJobMemoryDeleteResponse = None<Extra<T.AgentJobMemoryDeleteResponse, S['AgentJobMemoryDeleteResponse']>>;
export type CheckAgentJobMemoryStatsMostAccessedItem = None<Extra<T.AgentJobMemoryStatsMostAccessedItem, S['AgentJobMemoryStatsMostAccessedItem']>>;
export type CheckAgentJobMemoryStatsMostImportantItem = None<Extra<T.AgentJobMemoryStatsMostImportantItem, S['AgentJobMemoryStatsMostImportantItem']>>;
export type CheckAgentJobMemoryStatsResponse = None<Extra<T.AgentJobMemoryStatsResponse, S['AgentJobMemoryStatsResponse']>>;
export type CheckAgentJobMemorySearchItem = None<Extra<T.AgentJobMemorySearchItem, S['AgentJobMemorySearchItemResponse']>>;
export type CheckAgentJobMemorySearchResponse = None<Extra<T.AgentJobMemorySearchResponse, S['AgentJobMemorySearchResponse']>>;
export type CheckAgentJobExperimentRun = None<Extra<T.AgentJobExperimentRun, S['AgentJobExperimentRunResponse']>>;
export type CheckAgentJobOperatorIntervention = None<Extra<T.AgentJobOperatorIntervention, S['AgentJobOperatorInterventionResponse']>>;
export type CheckAgentJobPromoteDomainResearchProfileRequest = None<Extra<T.AgentJobPromoteDomainResearchProfileRequest, S['AgentJobPromoteDomainResearchProfileRequest']>>;
export type CheckAgentJobPromoteDomainResearchPortfolioRequest = None<Extra<T.AgentJobPromoteDomainResearchPortfolioRequest, S['AgentJobPromoteDomainResearchPortfolioRequest']>>;
export type CheckAgentJobPromoteDomainResearchRequest = None<Extra<T.AgentJobPromoteDomainResearchRequest, S['AgentJobPromoteDomainResearchRequest']>>;
export type CheckAgentJobPromoteDomainResearchResponse = None<Extra<T.AgentJobPromoteDomainResearchResponse, S['AgentJobPromoteDomainResearchResponse']>>;
export type CheckAgentJob = None<Extra<T.AgentJob, S['AgentJobResponse']>>;
export type CheckAgentJobDetail = None<
  Extra<T.AgentJobDetail, S['AgentJobDetailResponse']>
>;
export type CheckAgentJobEvidenceValue = None<Extra<T.AgentJobEvidenceValue, S['AgentJobEvidenceValue']>>;
export type CheckAgentJobEvidenceItem = None<Extra<T.AgentJobEvidenceItem, S['AgentJobEvidenceItem']>>;
export type CheckAgentJobEvidenceRequirement = None<Extra<T.AgentJobEvidenceRequirement, S['AgentJobEvidenceRequirement']>>;
export type CheckAgentJobEvidence = None<Extra<T.AgentJobEvidence, S['AgentJobEvidenceResponse']>>;
export type CheckAgentJobWorkspaceEntry = None<Extra<T.AgentJobWorkspaceEntry, S['AgentJobWorkspaceEntry']>>;
export type CheckAgentJobWorkspace = None<Extra<T.AgentJobWorkspace, S['AgentJobWorkspaceResponse']>>;
export type CheckAgentJobWorkspaceFile = None<Extra<T.AgentJobWorkspaceFile, S['AgentJobWorkspaceFileResponse']>>;
export type CheckAgentJobListResponse = None<Extra<T.AgentJobListResponse, S['AgentJobListResponse']>>;
export type CheckAgentJobTemplate = None<Extra<T.AgentJobTemplate, S['AgentJobTemplateResponse']>>;
export type CheckAgentJobTemplateListResponse = None<Extra<T.AgentJobTemplateListResponse, S['AgentJobTemplateListResponse']>>;
export type CheckAgentJobQuickStartClaudeBackendRequest = None<Extra<T.AgentJobQuickStartClaudeBackendRequest, S['AgentJobQuickStartClaudeBackendRequest']>>;
export type CheckAgentJobQuickStartDomainResearchRequest = None<Extra<T.AgentJobQuickStartDomainResearchRequest, S['AgentJobQuickStartDomainResearchRequest']>>;
export type CheckAgentJobQuickStartRepoBugTriageRequest = None<Extra<T.AgentJobQuickStartRepoBugTriageRequest, S['AgentJobQuickStartRepoBugTriageRequest']>>;
export type CheckAgentJobQuickStartBugTriageSwarmRequest = None<Extra<T.AgentJobQuickStartBugTriageSwarmRequest, S['AgentJobQuickStartBugTriageSwarmRequest']>>;
export type CheckAgentJobQuickStartBuildBreakSwarmRequest = None<Extra<T.AgentJobQuickStartBuildBreakSwarmRequest, S['AgentJobQuickStartBuildBreakSwarmRequest']>>;
export type CheckAgentJobQuickStartFrontendRegressionSwarmRequest = None<Extra<T.AgentJobQuickStartFrontendRegressionSwarmRequest, S['AgentJobQuickStartFrontendRegressionSwarmRequest']>>;
export type CheckAgentJobQuickStartRoleWorkflowRequest = None<Extra<T.AgentJobQuickStartRoleWorkflowRequest, S['AgentJobQuickStartRoleWorkflowRequest']>>;
export type CheckAgentJobRelaunchLineageNode = None<Extra<T.AgentJobRelaunchLineageNode, S['AgentJobRelaunchLineageNode']>>;
export type CheckAgentJobRelaunchLineage = None<Extra<T.AgentJobRelaunchLineage, S['AgentJobRelaunchLineageResponse']>>;
export type CheckAgentJobStats = None<Extra<T.AgentJobStats, S['AgentJobStatsResponse']>>;
export type CheckAgentJobSwarmAnalyticsPresetRow = None<Extra<T.AgentJobSwarmAnalyticsPresetRow, S['AgentJobSwarmAnalyticsPresetRowResponse']>>;
export type CheckAgentJobSwarmAnalytics = None<Extra<T.AgentJobSwarmAnalytics, S['AgentJobSwarmAnalyticsResponse']>>;
export type CheckAgentJobSwarmOutcomeCase = None<Extra<T.AgentJobSwarmOutcomeCase, S['AgentJobSwarmOutcomeCaseResponse']>>;
export type CheckAgentJobSwarmOutcomePresetRow = None<Extra<T.AgentJobSwarmOutcomePresetRow, S['AgentJobSwarmOutcomePresetRowResponse']>>;
export type CheckAgentJobSwarmOutcomeAnalytics = None<Extra<T.AgentJobSwarmOutcomeAnalytics, S['AgentJobSwarmOutcomeAnalyticsResponse']>>;
export type CheckAgentJobCheckpoint = None<Extra<T.AgentJobCheckpoint, S['AgentJobCheckpointResponse']>>;
export type CheckAgentJobChainDefinition = None<Extra<T.AgentJobChainDefinition, S['AgentJobChainDefinitionResponse']>>;
export type CheckAgentJobChainDefinitionCreate = None<Extra<T.AgentJobChainDefinitionCreate, S['AgentJobChainDefinitionCreate']>>;
export type CheckAgentJobChainDefinitionUpdate = None<Extra<T.AgentJobChainDefinitionUpdate, S['AgentJobChainDefinitionUpdate']>>;
export type CheckAgentJobChainDefinitionListResponse = None<Extra<T.AgentJobChainDefinitionListResponse, S['AgentJobChainDefinitionListResponse']>>;
export type CheckAgentJobFromChainCreate = None<Extra<T.AgentJobFromChainCreate, S['AgentJobFromChainCreate']>>;
export type CheckAgentJobChainStatus = None<Extra<T.AgentJobChainStatus, S['AgentJobChainStatusResponse']>>;
