//! Build the two snippets llvm-mca has to compare.
//!
//! The question a candidate raises is "what would fusing this save", and mca
//! can only answer it by costing two pieces of assembly: the sequence as it
//! stands, and the same region with the sequence replaced. Both have to be
//! fenced, both have to repeat enough times for the model to reach steady
//! state, and both have to make the same choice about whether repetitions
//! depend on each other -- otherwise the comparison measures the difference
//! between two harnesses rather than between two sequences.
//!
//! The replacement is a *stand-in*: mca cannot cost an instruction that does
//! not exist, so the fused form is modelled by a real instruction the caller
//! names. That makes the result "this sequence costs as much as N of those",
//! which is an assumption about the fused instruction's cost and is labelled
//! as one in the output.

use crate::pattern::{Pattern, RegisterPool};

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Mode {
    /// Each copy reads the previous copy's result: measures the dependence
    /// chain, which is what matters inside a loop-carried computation.
    Dependent,
    /// Copies are independent: measures how many the machine can overlap,
    /// which is what matters when the surrounding loop is unrolled.
    Independent,
}

impl Mode {
    pub fn parse(text: &str) -> Option<Mode> {
        match text {
            "dependent" | "latency" => Some(Mode::Dependent),
            "independent" | "throughput" => Some(Mode::Independent),
            _ => None,
        }
    }

    pub fn describe(self) -> &'static str {
        match self {
            Mode::Dependent => "dependent copies (latency)",
            Mode::Independent => "independent copies (throughput)",
        }
    }
}

pub struct Snippet {
    pub text: String,
    pub instructions: usize,
    pub copies: usize,
}

fn header(title: &str, mode: Mode, copies: usize) -> String {
    format!(
        "// {title}\n\
         // {copies} copies, {mode}\n\
         // Generated by candidate-coster. Region markers are required: an\n\
         // unfenced estimate covers the whole file and has been wrong by 3.4x.\n",
        mode = mode.describe()
    )
}

/// Render a pattern repeated `copies` times, fenced for llvm-mca.
pub fn emit_sequence(
    pattern: &Pattern,
    mode: Mode,
    copies: usize,
    title: &str,
) -> Snippet {
    let mut pool = RegisterPool::new();
    let mut body: Vec<String> = Vec::new();
    let mut carry: Option<String> = None;

    for _ in 0..copies.max(1) {
        let chain = match mode {
            Mode::Dependent => carry.clone(),
            Mode::Independent => None,
        };
        let lines = pattern.render(&mut pool, chain);
        if mode == Mode::Dependent {
            carry = pattern.result_register(&lines).or(carry);
        }
        body.extend(lines);
    }

    let mut text = header(title, mode, copies.max(1));
    text.push_str("# LLVM-MCA-BEGIN region\n");
    for line in &body {
        text.push_str("  ");
        text.push_str(line);
        text.push('\n');
    }
    text.push_str("# LLVM-MCA-END\n");
    // The trailing newline is not cosmetic. Without it llvm-mca reads the last
    // directive short -- "# LLVM-MCA-END loop" became region "loo" -- and the
    // run fails with a message about region markers that names no cause.
    Snippet {
        instructions: body.len(),
        copies: copies.max(1),
        text,
    }
}

/// Render the same region with each copy replaced by one stand-in instruction.
pub fn emit_fused(
    pattern: &Pattern,
    stand_in: &Pattern,
    mode: Mode,
    copies: usize,
    title: &str,
) -> Snippet {
    let _ = pattern;
    emit_sequence(stand_in, mode, copies, title)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse(text: &str) -> Pattern {
        Pattern::parse(text).expect("test pattern should parse")
    }

    #[test]
    fn a_region_is_fenced_and_ends_with_a_newline() {
        let snippet = emit_sequence(&parse("fmul fadd | 0>1"), Mode::Dependent, 4, "t");

        assert!(snippet.text.contains("# LLVM-MCA-BEGIN"));
        assert!(snippet.text.contains("# LLVM-MCA-END"));
        assert!(snippet.text.ends_with('\n'), "mca mangles a final directive");
    }

    #[test]
    fn an_edge_becomes_a_real_register_dependence() {
        let snippet = emit_sequence(&parse("fmul fadd | 0>1"), Mode::Dependent, 1, "t");
        let lines: Vec<&str> = snippet
            .text
            .lines()
            .filter(|l| l.trim_start().starts_with(|c: char| c.is_alphabetic()))
            .collect();

        let produced = lines[0].split_whitespace().nth(1).unwrap().trim_end_matches(',');
        assert!(
            lines[1].contains(produced),
            "the consumer must read the producer's register: {lines:?}"
        );
    }

    #[test]
    fn dependent_copies_chain_and_independent_ones_do_not() {
        let pattern = parse("fmul fadd | 0>1");
        let dependent = emit_sequence(&pattern, Mode::Dependent, 3, "t");
        let independent = emit_sequence(&pattern, Mode::Independent, 3, "t");

        assert_eq!(dependent.instructions, independent.instructions);
        assert_ne!(
            dependent.text, independent.text,
            "the two modes must differ, or the comparison measures nothing"
        );
    }

    #[test]
    fn a_pattern_with_no_edges_still_emits_legal_operands() {
        let snippet = emit_sequence(&parse("fsqrt fdiv"), Mode::Independent, 2, "t");

        for line in snippet.text.lines() {
            let trimmed = line.trim();
            if trimmed.starts_with("fsqrt") {
                assert_eq!(trimmed.matches(',').count(), 1, "fsqrt takes one source");
            }
            if trimmed.starts_with("fdiv") {
                assert_eq!(trimmed.matches(',').count(), 2, "fdiv takes two sources");
            }
        }
    }

    #[test]
    fn a_comparison_instruction_writes_nothing() {
        let snippet = emit_sequence(&parse("fcmp"), Mode::Independent, 1, "t");
        let line = snippet
            .text
            .lines()
            .find(|l| l.trim().starts_with("fcmp"))
            .unwrap()
            .trim();

        assert_eq!(line.matches(',').count(), 1, "fcmp reads two, writes none: {line}");
    }
}

#[cfg(test)]
mod width_tests {
    use super::*;
    use crate::pattern::Pattern;

    fn body(pattern: &str) -> Vec<String> {
        let parsed = Pattern::parse(pattern).expect("should parse");
        emit_sequence(&parsed, Mode::Dependent, 2, "t")
            .text
            .lines()
            .filter(|l| l.trim_start().starts_with(|c: char| c.is_alphabetic()))
            .map(|l| l.trim().to_string())
            .collect()
    }

    #[test]
    fn an_observed_width_is_used_rather_than_the_default() {
        // Godot's geometry code runs .2s; costing it as .4s prices a program
        // that was not run.
        let lines = body("fcmgt.2s bit.8b | 0>1");

        assert!(lines[0].contains(".2s"), "{lines:?}");
        assert!(!lines[0].contains(".4s"), "{lines:?}");
        assert!(lines[1].contains(".8b"), "{lines:?}");
    }

    #[test]
    fn a_width_makes_an_instruction_vector_even_without_a_table_entry() {
        let lines = body("fsub.2s");

        assert!(lines[0].starts_with("fsub v"), "{lines:?}");
        assert!(lines[0].contains(".2s"), "{lines:?}");
    }

    #[test]
    fn a_widening_instruction_keeps_its_own_pair_of_shapes() {
        // One arrangement cannot describe sxtl: it reads bytes and writes
        // halfwords, so the table wins over whatever width was recorded.
        let lines = body("sxtl.8h smlal.4s | 0>1");

        assert!(lines[0].contains("v0.8h") && lines[0].contains(".8b"), "{lines:?}");
        assert!(lines[1].contains("v1.4s") && lines[1].contains(".4h"), "{lines:?}");
    }

    #[test]
    fn a_pattern_with_no_width_still_renders_scalar() {
        let lines = body("fmul fadd | 0>1");

        assert!(lines[0].starts_with("fmul s"), "{lines:?}");
        assert!(!lines[0].contains('.'), "{lines:?}");
    }
}
