"""
Code patch proposals.

These are reviewable diffs generated by the Code Agent against a target codebase
represented in the KnowledgeDB (typically a git document source).
"""

from __future__ import annotations

from datetime import datetime
import uuid

from sqlalchemy import Column, DateTime, ForeignKey, JSON, String, Text, UniqueConstraint, Index
from sqlalchemy.dialects.postgresql import UUID

from app.core.database import Base


class CodePatchProposal(Base):
    __tablename__ = "code_patch_proposals"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    job_id = Column(UUID(as_uuid=True), ForeignKey("agent_jobs.id", ondelete="SET NULL"), nullable=True, index=True)
    source_id = Column(UUID(as_uuid=True), ForeignKey("document_sources.id", ondelete="SET NULL"), nullable=True, index=True)

    title = Column(String(500), nullable=False)
    summary = Column(Text, nullable=True)

    # Unified diff text
    diff_unified = Column(Text, nullable=False)

    # Structured metadata: files_touched, risks, tests_to_run, prompts, etc.
    proposal_metadata = Column("metadata", JSON, nullable=True)

    status = Column(String(24), nullable=False, default="proposed")  # proposed | applied | rejected

    created_at = Column(DateTime(timezone=True), default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime(timezone=True), default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    __table_args__ = (
        Index("ix_code_patch_proposals_user_status", "user_id", "status"),
        UniqueConstraint("job_id", name="uq_code_patch_proposals_job_id"),
    )
