"""Helpers for autonomous runtime state bootstrap and resume normalization."""

from __future__ import annotations

from copy import deepcopy
from typing import Any, Dict, Optional


_DEFAULT_RUNTIME_STATE: Dict[str, Any] = {
    "observations": [],
    "actions_taken": [],
    "findings": [],
    "artifacts": [],
    "goal_progress": 0,
    "execution_plan": [],
    "causal_experiment_plan": {},
    "causal_plan_generation_attempted": False,
    "plan_step_index": 0,
    "plan_generation_attempted": False,
    "execution_mode": "",
    "plan_completed": False,
    "subgoals": [],
    "subgoal_index": 0,
    "subgoal_chain_configured": False,
    "swarm_chain_configured": False,
    "swarm_child_jobs_count": 0,
    "swarm_roles_assigned": [],
    "swarm_fan_in_enabled": False,
    "swarm_fan_in_group_id": "",
    "tool_stats": {},
    "tool_priors": {},
    "critic_notes": [],
    "last_critic_iteration": 0,
    "critic_last_trigger": {},
    "critic_last_trigger_iteration": 0,
    "critic_trigger_counts": {},
    "last_progress": 0,
    "stalled_iterations": 0,
    "repeated_action_iterations": 0,
    "last_action_signature": None,
    "recovery_actions_used": 0,
    "progress_history": [],
    "forced_exploration_attempts": 0,
    "forced_exploration_used": 0,
    "forced_exploration_successes": 0,
    "forced_exploration_failures": 0,
    "forced_exploration_history": [],
    "tool_cooldowns": {},
    "tool_cooldown_blocks": 0,
    "tool_selection_effective_mode": "",
    "tool_selection_ab_assignment": {},
    "tool_selection_mode_metrics": {},
    "tool_selection_mode_override": "",
    "tool_selection_fallback_events": [],
    "counterfactual_last": [],
    "counterfactual_logged_iterations": 0,
    "counterfactual_last_iteration": 0,
    "tool_selection_goal_stage": "",
    "selection_explainability_last": {},
    "selection_explainability_logged_iterations": 0,
    "memory_context": "",
    "injected_memories": [],
    "injected_memory_payloads": [],
    "memory_runtime": {},
    "memory_extraction": {},
    "memory_extraction_policy": {},
    "customer_profile": None,
    "customer_context": "",
    "project_profile": {},
    "skill_profile": {},
    "skill_profile_metrics": {},
    "feedback_learning": {},
    "goal_contract_last": {},
    "goal_contract_satisfied_iteration": 0,
    "approval_checkpoint_pending": None,
    "approval_checkpoint_events": [],
    "approval_checkpoint_seen": [],
    "approval_override_action": None,
    "step_events": [],
    "scope_guard_events": [],
    "scope_guard_blocks": 0,
    "scope_events": [],
    "verification_actions": [],
    "verification_attempts": 0,
    "verification_successes": 0,
    "summarization_actions": [],
    "summarization_attempts": 0,
    "summarization_successes": 0,
    "execution_graph_edges": [],
    "execution_graph_nodes": [],
    "decision_parse_metrics": {"parse_success": 0, "parse_retry": 0, "parse_repair": 0, "parse_failure": 0},
    "execution_plan_version": 1,
    "plan_replan_count": 0,
    "plan_progress": 0,
    "reflections": [],
    "hypotheses": [],
    "evidence_ledger": [],
    "plan_critiques": [],
    "delegated_subtask_ids": [],
    "delegated_subtask_results": {},
    "review_requests": [],
    "review_responses": [],
    "code_execution_history": [],
    "coding_workspace_id": None,
    "coding_modified_files": [],
    "coding_command_history": [],
    "document_workspace": None,
}


def initialize_runtime_state(checkpoint_state: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Create a fully normalized runtime state, optionally overlaying a checkpoint."""
    state = deepcopy(_DEFAULT_RUNTIME_STATE)
    if isinstance(checkpoint_state, dict):
        state.update(checkpoint_state)
    state["last_progress"] = int(state.get("goal_progress", 0) or 0)
    return state
